# DeepSource configuration file
# Learn how to configure: https://docs.deepsource.com/docs/configuration
version = 1
test_patterns = ["**/*Test*.java"]

[[analyzers]]
  name = "java"
  enabled = true

[[analyzers]]
  name = "kotlin"
  enabled = true

[[analyzers]]
  name = "swift"
  enabled = true
